app:
  build: .
  command: python -u app.py
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=scraping_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - mongodb-data:/data/db
  ports:
    - 27017:27017